export enum PermissionID {
  CreateNewPermission = "create_new_permission",
  CreateNewRole = "create_new_role",
  CreateNewRolePermission = "create_new_role_permission",
  CreateNewSetting = "create_new_setting",
  CreateNewUser = "create_new_user",
  CreateNewUserRole = "create_new_user_role",
  DeletePermission = "delete_permission",
  DeleteRole = "delete_role",
  DeleteRolePermission = "delete_role_permission",
  DeleteSetting = "delete_setting",
  DeleteUserRole = "delete_user_role",
  ReadPermissionDetails = "read_permission_details",
  ReadRoleDetails = "read_role_details",
  ReadSettingDetails = "read_setting_details",
  ReadUserDetails = "read_user_details",
  UpdatePermissionDetails = "update_permission_details",
  UpdateRoleDetails = "update_role_details",
  UpdateSettingDetails = "update_setting_details",
  UpdateUserDetails = "update_user_details",
  ViewAdminPage = "view_admin_page",
  TestRole = "test_role",
}
